// #include "AD/AD.ino"
// #include "AUTOMATION/AUTOMATION.ino"
// #include "EUCLID/EUCLID.ino"
// #include "LOGIC/LOGIC.ino"
// #include "MASTER_CLOCK/MASTER_CLOCK.ino"
// #include "RND_NS/RND_NS.ino"
// #include "RUNGLER/RUNGLER.ino"
// #include "SAMPLER2/SAMPLER2.ino"
// #include "SEQ_DRIVER/SEQ_DRIVER.ino"
// #include "VCA/VCA.ino"
#include "VCO/VCO.ino"
